// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdccqwdrnkuzgqbttlgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkY2Nxd2Rybmt1emdxYnR0bGduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyOTc4MTEsImV4cCI6MjA2ODg3MzgxMX0.CAevqjBy4ML_m5fJQSoXwq4j0rwTbOXkgcVf1OHPFgM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});